### ISSUE TITLE
bug: off-by-one error in quality calculation

### ISSUE THREAD

**Issue by KaneTW** [ffxiv-teamcraft/simulator#4]
https://i.imgur.com/vp5r6zF.png
Given the above craft and stats, the game calculates 808 progress.

https://ffxivteamcraft.com/simulator/27233/33457/n4z4JsLKwGfhPETVBcG3
Teamcraft calculates 809.

**Comment by Supamiu** [comment]
Got another one:
![](https://cdn.discordapp.com/attachments/355098552122343424/600174614097952791/unknown.png)
![](https://media.discordapp.net/attachments/355098552122343424/600174626122760202/unknown.png)

Seems to only affect progress so far.

**Comment by Vikingeets** [comment]
It looks like Delicate Synthesis uses ceil instead of floor: https://github.com/ffxiv-teamcraft/simulator/blob/053749a0a8b751b844b5641303f3b555d26f3238/src/model/actions/other/delicate-synthesis.ts#L47
Browsing the code, I see Trained Hand does the same thing: https://github.com/ffxiv-teamcraft/simulator/blob/053749a0a8b751b844b5641303f3b555d26f3238/src/model/actions/other/trained-hand.ts#L51

**Comment by Supamiu** [comment]
That's such a stupid mistake, thanks for pointing it out !
